### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by physixfan** [kngxscn/backup-renren-status#2]
在运行到某一页的时候就开始报错了（每次具体页码数不一样）...

> Traceback (most recent call last):
  File "brs.py", line 78, in <module>
    status_list = parse_html(session, renren_id)
  File "brs.py", line 64, in parse_html
    commentsArray = comments_json_obj['comments']
KeyError: 'comments'

**Comment by Jiaqi202** [comment]
> 在运行到某一页的时候就开始报错了（每次具体页码数不一样）...
> 
> > Traceback (most recent call last):
> > File "brs.py", line 78, in 
> > status_list = parse_html(session, renren_id)
> > File "brs.py", line 64, in parse_html
> > commentsArray = comments_json_obj['comments']
> > KeyError: 'comments'

我也遇到了同样的报错。请问你有解决嘛
